# Generated by Django 2.2 on 2020-09-28 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('slug_movie', models.SlugField(blank=True, max_length=250)),
                ('slug_series', models.SlugField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(blank=True, max_length=250, null=True)),
                ('description', models.TextField()),
                ('year', models.PositiveIntegerField(default=2000)),
                ('banner', models.URLField(blank=True, default='', null=True)),
                ('age', models.PositiveIntegerField(default=3)),
                ('movie_trailer', models.URLField(blank=True, null=True)),
                ('runing_time', models.PositiveIntegerField(default=120)),
                ('country', models.CharField(default='USA', max_length=200)),
                ('rate', models.DecimalField(decimal_places=2, default=7.4, max_digits=3)),
                ('quality', models.CharField(default='HD', max_length=15)),
                ('link', models.URLField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.Category')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250)),
                ('banner', models.URLField(blank=True, null=True)),
                ('trailer', models.URLField(blank=True, null=True)),
                ('year', models.PositiveIntegerField(default=2000)),
                ('description', models.TextField()),
                ('age', models.PositiveIntegerField(default=3)),
                ('country', models.CharField(default='USA', max_length=200)),
                ('rate', models.DecimalField(decimal_places=2, default=7.4, max_digits=3)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.Category')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='SeriesImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField()),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series_photo', to='movie.Series')),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=250)),
                ('season_num', models.IntegerField(default=1)),
                ('banner', models.URLField(blank=True, null=True)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series_season', to='movie.Series')),
            ],
        ),
        migrations.CreateModel(
            name='MovieImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_photo', to='movie.Movie')),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=250)),
                ('episode_num', models.IntegerField(default=1)),
                ('banner', models.URLField(blank=True, default='', null=True)),
                ('episode_trailer', models.URLField(blank=True, null=True)),
                ('air_date', models.DateField(default='2020-08-07')),
                ('runing_time', models.PositiveIntegerField(default=120)),
                ('rate', models.DecimalField(decimal_places=2, default=7.4, max_digits=3)),
                ('quality', models.CharField(default='HD', max_length=15)),
                ('link', models.URLField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('season', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='season', to='movie.Season')),
                ('series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='series_movie', to='movie.Series')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
